spinnaker/igor

igor-web/igor-web.gradle

reference /opt in startScripts

---

build.gradle
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsMasters.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy

- Each Jenkins shard gets their own hystrix pool
- No fallback behavior (currently), rather all hystrix activity will result in a 429 being raised

Introduced Hystrix around the calls to jenkins shards

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy
igor-web/src/main/resources/hystrix.properties

- This is a placeholder, hystrix configuration will get folded into the Spring environment shortly

Add hystrix.properties

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.groovy

Findall returns an empty list when nothing matches, removeall returns false.

provider/docker: Removeall failed

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.groovy

Fix Jedis resource leak

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/health/PollingMonitorHealth.groovy

Igor will start without polling agents

---

README.md

This adds information about the travis integration to the README.md

Update README.md with travis information

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverter.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

* Fix travis property endpoint
* Add test for travis property endpoint
* add explicit return to methods
* add space around if statements
* remove some unused code

Property endpoint for travis is not working, added fix for it

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/BuildArtifact.groovy

When I introduced generic build for jenkins I introduced a bug. Artifacts are not present in the results.
This fixes it.

This makes igor return artifacts from jenkins builds again

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy

Only functional change is to not log `sending build events for builds between X and Y` when there is only one new build

Refactor travis build monitor

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

* move Overrides to top.
* make accessToken and account fetching private.

Refactor TravisService

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

This makes the TravisBuildMonitor recover after travis downtime.
I have tested this locally by turning off wifi and then turning on wifi after calls to travis has failed.

Use hysterix around travis calls used by TravisBuildMonitor

---

README.md

docker: Add section detailing docker config in Igor

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.groovy

provider/docker: Respond to trigger events w/o digest

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/health/PollingMonitorHealth.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

removed unused {} as Action0 from subscribe method
gave healthcheck a little more time to work
made polling on new thread
removed noisy list masters message from info controller

make polling more parallel

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/model/DockerRegistryAccounts.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/service/ClouddriverService.groovy

docker: skip digest checks when this is disabled in clouddriver

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

bean initialization issue when you have more than one bean reference

changed discovery client to a provider to overcome spring

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy

@spinnaker/netflix-reviewers FYI

okhttp connectionpool fix for timeout errors

---

build.gradle
igor-web/igor-web.gradle

Increment Spinnaker Dependencies 0.63.0 to get stackdriver support
@ttomsu

Upgrade to dependencies 0.63.0 and add stackdriver.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/CommitController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/github/CommitControllerSpec.groovy

Should replace https://github.com/spinnaker/orca/pull/853
PTAL @dzapata @tomaslin

Fix GetCommitList from Github. Invert from and to

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitHubConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitHubProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JedisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/StashConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/StashProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisCache.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildCacheSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCacheSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

This is dependant on spinnaker/kork#62 - do not merge
Also includes:
- elimination of some Autowired fields into Configuration classes
- updating some existing ConfigurationProperties to be imported by a Configuration instead of being their own Configuration
- cleanup of some redis calls to ensure connections get closed

Converts Value to ConfigurationProperties.

---

igor-web/igor-web.gradle

switch ospackaging to project conventions

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

This offers some protection around the loss (or flush) of an underlying redis store.
Currently, igor will publish events for _all_ jenkins builds (regardless of completion date) if redis is flushed.

Only publish events to echo if a build has been seen at least once

---

build.gradle

Update spinnaker-dependencies for monitoring support.

---

halconfig/igor.yml

Base igor halconfig

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

Slim build & gradle plugin bump

---

halconfig/igor.yml

(halconfig) fix redis connection & remove circular service dependency

---

build.gradle

updates kork/jackson/spectator

chore(dependencies) update to spinnaker-dependencies 0.84.0

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/CommitController.groovy

While investigating some unrelated issues, I noticed a huge amount of errors in our logs just revolving around poor handling of null values.
@spinnaker/reviewers PTAL

fix(web): Handling two different cases of NPEs

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

- Removed the use of parallelStream while processing builds
- parallelStream may lead to a concurrency issue with redis read/write for close enough builds
- Refactored method for readability

fix(jenkins): Fixing missed build events on concurrent builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

Revert "fix(jenkins): Fixing missed build events on concurrent builds"

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Config.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/model/ConfigSpec.groovy

Travis recently updated the api to support deep merge for environment variables.
No need to inject all the variables needed for the build, just override what you want.

feat(travis): override environment variables instead of replacing.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/Request.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

This is a new part of the travis api that allows us to trace the concrete travis build igor triggered.

feat(travis/triggerBuild): trace the unique build igor triggered.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

Jenkins returns a 409 when a job is disabled and you try to trigger it. This is not very helpful.
The job config has `buildable` set to `false` on disabled jobs, so we can use that to provide a better error message to users.

fix(jenkins): provide better error when a job is disabled

---

build.gradle
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy

cc @gardleopard - please take for a spin.
Merging into `boot-upgrade` branch

chore(springBoot): Upgrade to Spring Boot 1.5.4

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

- Adjusted algo to account for the first time a build is encountered

fix(jenkins): Process brand new builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

- Only log on actions, removed some logs causing noise

chore(jenkins): Make logs less chatty

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

@spinnaker/netflix-reviewers PTAL

chore(web): Selectively applying structured logs

---

build.gradle

upgrading spinnaker-dependencies to pull in logstashEncoder

chore(dependencies): upgrade spinnaker-dependencies to 0.117.0

---

igor-web/config/igor.yml
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Account.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

* add configuration numberOfRepositories for travis
* remove calls to /repos that are not returning results

feat(travis) configurable number of repositories to track on each poll

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildCacheSpec.groovy

Create the job list using the completed job cache only.

perf(travis) fetch list of jobs a lot faster

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

With the new lookback window, we were checking if the start time was before the window, and if so ignoring it. This caused builds that were longer than the lookback window to not to fire an event.
This changes the calculation to check whether the build end time is outside the lookback window.

fix(buildevents): lookback window checks end time, improved logs

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

fix(lookback): add times together correctly

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/health/PollingMonitorHealth.groovy

fix(discovery): Removing spring cyclic health indicator deps

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java

fix(docker): Making the redis key correct

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/AbstractRedisCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.java

refactor(cache): Replace usage of redis keys command with scan

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitlabCiConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitlabCiProperties.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/GitlabCiClient.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/model/Pipeline.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/model/PipelineStatus.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/model/PipelineSummary.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/model/Project.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiPipelineUtis.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiResultConverter.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/client/GitlabApiCannedResponses.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/client/GitlabCiClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiPipelineUtisSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiServiceSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

This PR fixes Igor part of https://github.com/spinnaker/spinnaker/issues/2173

feat(gitlab-ci): Implement triggering of Spinnaker pipelines by Gitlab CI pipelines

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

We sometimes see properties files not be available on Jenkins immediately, which causes Orca to run with an empty properties list on a triggered build.

fix(jenkins): add retrySupport to getProperties call

---

Dockerfile
Dockerfile.slim

See https://github.com/spinnaker/spinnaker/issues/2298

chore(docker): Upgrade base image (#2298)

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/admin/AdminController.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/PollAccess.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/PollContext.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/PollEvent.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/admin/AdminControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

Wee little admin api to re-index pollers without sending notifications.

feat(web): Adding admin reindex api

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java

It occurred to me while running the migration that if network traffic interrupts the scan process, we've done a bunch of work without any actual output. This refactor is more resilient for Spinnaker deployments that are huge.
Changes:
1. Scan operations now retry on errors (wow!)
1. Each scan operation's results are migrated immediately, rather than being aggregated and processed in a second phase.

refactor(docker): Incrementally migrate keys on each scan result

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java

fix(dynomite): Fixing dyno scan usage

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

fix(docker): Fixing Groovyism: Defer problems to runtime, thats fine

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

Also includes more logging, and a monitoring fix on guarded updates.

fix(docker): Fixing NPE when an image in list is null

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java

fix(docker): s/registry/repository

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/health/PollingMonitorHealth.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

Updates the PollingMonitor HealthIndicator to no longer
mark the service as DOWN if a PollingMonitor has not
updated recently enough.
Typical deployment footprint for igor is a single instance
due to polling coordination state, so taking that instance
DOWN on any one monitor failure is bad for all clients.

fix(health): non fatal healthindicator

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/admin/AdminController.java

fix(polling): Non-reachable endpoint for fast forwarding a poller

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java

fix(travis): Fix a code path that didn't fetch logs when it should

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.java

Closes https://github.com/spinnaker/spinnaker/issues/2864
cc @sushantk

perf(redis): Replace all `keys` command calls with `scan`

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/LockManagerConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

- build monitors locking
- allows running multiple igor for polling

feat(*) Locking support

---

build.gradle

- update spin dependencies to 0.157.2

chore(dependencies): Bump spinnaker dependencies to 0.157.2

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
issue: https://github.com/spinnaker/spinnaker/issues/2878

fix(jenkins): use lowercase header for job location in jenkins

---

build.gradle

- update spin dependencies to 0.157.5

chore(dependencies): Bump spinnaker dependencies to 0.157.5

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/LockManagerConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/LockManagerConfigProperties.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/LockService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy

- Added a config for lock properties

refactor(lock): Make locking more configurable

---

build.gradle

chore(dependencies): Update spinnaker dependencies to 0.157.7

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/ScmDetails.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

same as https://github.com/spinnaker/igor/pull/273, but for `release-1.8.x`

fix(jenkins) return multiple scms when jenkins has multiple scms and remoteUrl calls

---

build.gradle

chore(dependencies): Update spinnaker dependencies to 0.157.9

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

- Debugging an issue with no echo events when running > 1 nodes

perf(jenkins): Experimenting using stream instead of parallel streams

---

igor-web/src/main/java/com/netflix/spinnaker/igor/health/EchoServiceHealthIndicator.java

- validates connectivity to echo
- must pass at least once before Igor goes UP
- up by default if echo is not configured

feat(echo): Adding a health indicator for echo

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/LockService.java

chore(lockService): Adding missing header text

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

- the stop method should live in parent class instead of Jenkins monitor

fix(pollers): Moving `@Predestroy` method to shutdown scheduler to parent class

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/admin/AdminController.java

Just improve the error response message.

feat(admin): improve error response

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/auth/AuthRequestInterceptor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/exceptions/UnhandledDownstreamServiceErrorException.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/AbstractCommitController.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/CommitController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/CommitController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/gitlab/CommitController.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/stash/CommitController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

Just a bunch of exception handler cleanup.
There's a whole lot of referencing exception classes defined in controllers from lower-level classes, which I'd like to cleanup in a separate thing.

chore(web): Cleanup rest exception handlers

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

Cleaning up some more logs in igor. Moved some things to metrics that should be metrics, changed log levels to trace for some trace-worthy level logs and removed some others.

chore(*): Reduce logging noise; convert some logs to metrics

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

fix(travis): cherry-pick #310 commit into release 1.9

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to …

fix(travis): cherry-pick #310 commit into release 1.8

---

build.gradle
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy

Get some metrics on those jenkins clients. Wowzers.

feat(jenkins): Instrument jenkins clients

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

I suspect this is only the tip of the iceberg but trying to get relevant status codes / messages out of endpoints when they stray from the happy path seems worthwhile.

fix(http): make the getProperties endpoint return HTTP 404 status

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java

Some patches has affected the in flight build tracing for the travis
integration. We have got many users that has complained about pipelines
not getting triggered and this should mitigate that problem.

fix(travis/build_tracking): fix for travis build tracking

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactExtractor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/CustomJinjaTemplate.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/JinjaTemplate.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/JinjaTemplateService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/StandardJinjaTemplate.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericBuild.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/resources/docker.jinja
igor-web/src/main/resources/jar.jinja
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactExtractorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

refactor(artifacts): Move artifact logic from echo to igor
This commit just moves the logic for parsing artifacts from builds
from echo to igor.
feat(artifacts): Add igor endpoint to get artifacts from a build

 feat(artifacts): Add igor endpoint to get artifacts from a build

---

igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java
igor-web/src/test/java/com/netflix/spinnaker/igor/RedisConfig.java

Test that igor starts up with a very basic config, only mocking out redis.

test(core): Simple startup integration test

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/OkHttpClientBuilder.java

fix(cf): okhttp3 connector now trusts all certificates

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ConcourseClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ResourceService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/Build.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/Resource.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java

Supporting API for a new Concourse stage:

feat(stages): Add support for Concourse stage

---

igor-web/igor-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

updates kork to 5.3.4
updates fiat to 1.0.4
updates spinnaker-gradle-project to 6.5.0

chore(dependencies): externalize versions to properties

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitor.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/health/EchoServiceHealthIndicator.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java

Without this the log is spammed with warnings about missing auth headers

chore(auth): Allow anonymous requests from Igor to Echo

---

gradle.properties
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/model/DockerRegistryAccounts.groovy

Updates JenkinsClient to use helper method to construct proxy instances.
Adds allowAnonymous around some calls to eliminate logging noise.

chore(dependencies): kork 5.4.8

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java

`echoService` is an `Optional`

fix(gitlab): Don't send events to echo if not enabled

---

build.gradle
igor-bom/igor-bom.gradle
settings.gradle

This simplifies dependency resolution downstream

feat(igor-bom): publish igor-bom

---

gradle.properties
igor-web/src/main/java/com/netflix/spinnaker/igor/artifacts/ArtifactController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/artifacts/ArtifactService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactServiceSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/artifacts/TestArtifactService.java

Carry https://github.com/spinnaker/gate/pull/837 to artifact services.

feat(artifacts): allow release status to be propagated to artifact svc

---

gradle.properties

Just making sure the new IDEA changes to the plugins don't cause problems if the IDEA files don't exist in the repo.

chore(gradle): Upgrade the Spinnaker gradle plugin

---

README.md
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/ArtifactServiceProvider.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusEventPoster.java
igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java

Revert "fix(nexus): add nexus name endpoint and artifact location (#506)"

---

gradle.properties
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy

Fixes serialization issue in fiat-api version mismatch with new values in Authorizations enum

fix(fiat-api): fiatVersion 1.7.1

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy

Minor change to clean up a bit InfoController.

style(igor): Removed unused variables in InfoController

---

gradle.properties
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParser.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParserSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

See https://github.com/spinnaker/spinnaker/issues/5134
Dependent on https://github.com/spinnaker/kork/pull/419 for a Spring Boot dependency upgrade

chore(dependencies): Upgrade Spring Boot to 2.2.1

---

.github/workflows/pr.yml

More experimentation with GH Actions

chore(ci): Do GHA build on master and release branches

---

README.md

Includes new GitHub Actions badge

chore(ci): Add CI badge(s) to README

---

igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildController.java

This API calls CodeBuild to stop build. Orca calls this API when a user manually cancelled an pipeline execution.

feat(codebuild): Add stopBuild API in AwsCodeBuildController

---

igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccountSpec.groovy

This API will be called by orca to fetch S3 artifacts produced by CodeBuild
so that these artifacts could be binded and consumed by downstream stages.

feat(codebuild): Add getArtifacts API for AWS CodeBuild

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy

- RPC issues between igor and jenkins are hard to diagnose without proper visibility
- drop InstrumentedProxy metrics in favor of the more standard OkHttpMetricsInterceptor

chore(logs/metrics): add logging and metrics to JenkinsClient

---

igor-core/igor-core.gradle
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java

This PR makes Igor pluggable, similar to https://github.com/spinnaker/clouddriver/pull/4383

feat(plugins): igor supports plugins

---

igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginsBuildMonitor.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/model/PluginRelease.java

Debugging igor is a huge pain.

chore(plugins): Logging improvemtns on new plugin releases

---

igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginsBuildMonitor.java

This is going to be the end of me.

chore(plugins): Add some additional logging

---

igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginCache.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginsBuildMonitor.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/RedisPluginCache.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginInfo.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseService.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/model/PluginRelease.java
igor-monitor-plugins/src/test/groovy/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseServiceSpec.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java

feat(plugins): Track plugin releases by plugin id

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java

Converting it to use new client provider

fix(misc): Move to new client provider for building retrofit client

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy
igor-web/config/igor.yml
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/5853

feat(travis): make it possible to specify the list of repos to scan

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/WerckerConfig.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerClientSpec.groovy

- Minor change. Remove OkHttp2 usage.

fix(misc): Remove okhttp2 usage and move to provider impl

---

igor-web/igor-web.gradle

-- Adding new `kork-cloud-config-server` as dependency.

fix(misc): Add config server dependency

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/service/ClouddriverService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/service/TaggedImageList.groovy

fetching `date` field from docker metadata, and adding a log statement which will help us figure out the time difference between including all details from the registry to just include some of them.

feat(date): adding date to docker images metadata, and log statement with timing

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/service/TaggedImageList.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy

We have recently added docker metadata information, like build number, commit id, and so on. This change is adding branch information as well.

feat(dockerBranch): add branch info for docker images

---

README.md

I extracted that descripton from the comment in the code
Fixes https://github.com/spinnaker/spinnaker/issues/6143

Document the `pollingEnabled` setting

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy

The pending key has a TTL of 10 minutes which means that if an Orca Jenkins stage is canceled and then restarted within that time window Igor returns an invalid queued build number which stalls the stage.  
This solution adds the Orca stage start time as a value to the pending key.
Orca change: https://github.com/spinnaker/orca/pull/4045

fix(jenkins): Add startTime to pendingKey to account for restarted Jenkins stage which have identitical X-SPINNAKER-EXECUTION values

---

build.gradle
gradle.properties
igor-bom/igor-bom.gradle
igor-core/igor-core.gradle
igor-monitor-artifactory/igor-monitor-artifactory.gradle
igor-monitor-plugins/igor-monitor-plugins.gradle
igor-monitor-travis/igor-monitor-travis.gradle
igor-web/igor-web.gradle

chore(deps): update kork to 7.107.0, use new maven coordinates

---

gradle.properties

chore(dependencies): Autobump korkVersion 

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java

This reverts commit f8b365683dfd152481d42fb96ac36ef64a9a96f1.
Reverted in favour of https://github.com/spinnaker/orca/pull/4093.

Revert "feat(travis): Adds more info to triggered Travis builds by

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/scheduled_release.yml

closes: https://github.com/spinnaker/spinnaker/issues/6611

chore(ci): update setup-java GHA to v2

---

build.gradle
igor-web/igor-web.gradle

This change makes the project compatible with Gradle 7

chore(build): Gradle 7 compatibility

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

If a user has deleted the log for a job in Travis or it has expired due to old age, Spinnaker may fail to display the list of builds in the start manual execution box, even though there are other builds/jobs available. This fix will just filter these (and other) failures, and instead of failing completely, it will print an error message in the Igor log. The `catch` clause will print a log line at level "INFO" for cases where the log has expired (which can happen from time to time) and at WARN level for other (actual) errors.

fix(travis): Don't panic if log fetching fails

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

Get project and location to create a build using build options 
Google Cloud Build Api https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.builds
Issue https://github.com/spinnaker/spinnaker/issues/6600
Local Spinnaker Instance with build defined in issue above.

feat(provider/google): Support private worker pool in gcb CI
