igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Project.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/JobList.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

This is meant to address https://github.com/spinnaker/spinnaker/issues/605.
I'm able to hit `http://localhost:8080/jobs/<JenkinsName>/` and see a list of jobs with the expected names:
```json
[
"Job1",
"Folder1/job/Job2",
"Folder1/job/Folder2/job/Job3"
]
```
Its also likely that a few endpoints will need to be updated since they currently have the job names in the middle of other parameters, such as "/jobs/{jobName}/builds" which could be troublesome.

Capture Jenkins job names correctly when the folder plugin is being used

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/BuildController.groovy

I've been seeing a lot of exceptions in the logs around `getQueueLocationLegacy` but am not sure who is calling it or what they are trying to access - we just end up with a stacktrace that looks like this:
```
2016-01-04 19:11:15,889 ERROR org.apache.juli.logging.DirectJDKLog:182 [http-nio-7002-exec-1] [log] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is retrofit.RetrofitError: 404 Not Found] with root cause
retrofit.RetrofitError: 404 Not Found
at retrofit.RetrofitError.httpError(RetrofitError.java:40)
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
at com.sun.proxy.$Proxy166.getQueuedItem(Unknown Source)
at …
```

include message when throwing exceptions from BuildController

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/ParameterDefinition.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/InfoControllerSpec.groovy

* delegate error logging to the exception handlers
* create exception handlers to propagate specific error messages back to the caller
* validate choice parameter types against job config - we can't get a JSON response back from Jenkins when it throws exceptions, but we can perform the validate up front before even attempting to send the request to the Jenkins
@tomaslin please review

validate param choices, include messages in responses

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy

you can now set a client.timeout value in your igor.yml file and it will override the default value of 30 seconds. 
Note: the time is in milliseconds so ```client.timeout: 60000```

allow timeout for jenkins http client to be modified by a property

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/history/EchoService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/history/model/BuildEvent.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/history/model/DockerEvent.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/history/model/Event.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/BuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/BuildMonitorSpec.groovy

I was incorrectly using the `details` field of the event data sent to Echo rather than `content`. 
I also switched formatting of `imageId` from `$registry/$repository:$tag` to the image key stored in redis, for simplicity.
@duftler

provider/docker: Send proper event details to echo.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy

Hello @robfletcher @ajordens @tomaslin !
This PR is to add the ability for the jenkins stage to be cancellable. The change involves changes on both Orca and Igor.
- Orca: Jenkins stage now implements the `CancellableStage` interface and there is now a new task that hits a `stop` endpoint on Igor
- Igor: There are two different apis for canceling a jenkins job. The first is `/job/{jobName}/{buildNumber}/stop` which will stop a job that is currently running. The other one is `/queue/cancelItem` which will remove a queued job. There is also some weird jenkins api issues I ran into that I commented on inline.
- Deck: I thought about adding some sort of flag on the jenkins stage that would allow the user to opt into the cancellable aspect of the stage, but the more I thought about it the more …

Adding support for igor to stop and cancel jenkins jobs

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

Renaming the jenkins build monitor to JenkinsBuildMonitor.

Rename BuildMonitor to JenkinsBuildMonitor

---

README.md
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericBuild.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/ScmDetails.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Commit.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

* Same method called for Jenkins and Travis integration
* Travis now returns scm info
* Minor update in README.md
The point of this is to make BuildController more generic, so it is easier to add new ci integrations. Also using igor classes to control what we expose to the other spinnaker services makes it easy to see what fields that are used from builds throughout the spinnaker platform.

Refactor build status endpoint in BuildController

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/RepoRequest.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/RepoWrapper.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/TriggerResponse.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverter.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

* https://travis-ci.org confirmed working
* https://travis-ci.com (travis pro) @aioue will test it on travis-pro.
* Does not work on travis enterprise (travis enterprise is way behind the other versions)
The endpoint we are using is in beta. https://docs.travis-ci.com/user/triggering-builds
The builds in the screenshot are triggered from travis using 
`curl -s -X PUT http://localhost:8080/masters/travis-ci/jobs/repo/slug`

Add support for triggering travis builds with igor

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Commit.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

You can choose to listen to org/repo for all builds of the project, or you can choose a specific branch like org/repo/branch.
I have checked how jenkins work with https://wiki.jenkins-ci.org/display/JENKINS/Multi-Branch+Project+Plugin and this gives almost the same experience.

Add support for branches in the travis integration

---

igor-web/config/igor.yml
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

The workflow we are implementing for using travis with spinnaker at schibsted is as follows.
1. We have a spinnaker system user in github
2. To get your builds into spinnaker, you grant the spinnaker system user access to the repository
Now igor syncs travis and github for us and makes new builds appear.

Sync repositories in travis for the spinnaker github user

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

The groupKey does not need to prefix with `travis-`. It is already done here:
https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy#L63

Include travis master in log if repository synchronization fails

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JedisConfig.groovy

This lets users override the redis timeout in igor.

Make redis.timeout override for igor fixes spinnaker/spinnaker#877

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

We discovered that pull request builds are registered as the branch you do the pull request against with `"pull_request":true` in the [response](https://docs.travis-ci.com/api#builds) from travis. This pull request makes igor identify these pull requests and creates virtual branches for the target branches. A pull request to master will be registered to spinnaker as the branch `pull_request_master`.
The idea behind this is that you can create pipelines in spinnaker that listens to pull requests and run more test on them than you do in travis. You can bake and deploy them to check them out.
The current code in igor will let pull requests trigger pipelines that listens on the target branch for the pull request.

Travis - make virtual branches for pull requests

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

This PR makes all writes from TravisBuildMonitor to BuildCache
include a TTL. The TTL defaults to 60 days and can be overridden
by the property travis.cachedJobTTLDays.
setBuildCacheTTL() is called every time TravisBuildMonitor starts
(igor starts) that checks is all jobs in the BuildCache has ttl
set. If not, it will set it.

Set TTL on BuildCache items for travis.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverter.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverterTest.groovy

The TravisBuildMonitor only considers started as running as it is now. This PR makes igor aware of the `created` state and translates that into a running build as well.
This is an edge case that I have not seen in travis, but I'm sure we will see it some day.

Travis - consider 'created' as a running state

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

This makes the build list from travis only show builds relevant to your choosen branch
when you trigger pipelines from deck.
* If you have choosen to listen to a specific branch, only builds of that branch shows up.
* If you have choosen to listen to the virtual branch tags, only tag builds shows up.
* If you listen to PRs against a specific branch, only PR builds shows up.
* If you listen to all builds (org/repo), all the builds show up.

Filter build lists from travis

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericBuild.groovy

This makes it possible to use this name when creating the package data to show in cluster view later in spinnaker.

Add the job name to event sent to echo

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy

If the travis api returns old builds when the travisBuildMonitor fetches builds, we need to filter them out so that we don't get another event pushed to echo after the TTL has ran out.

Ignore travis builds that are older than the travis cache TTL

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

This will simplify tracking down the spurious trigger cause, and should be logged anyhow for traceabilty into what was deployed.
@duftler

docker: Log changes to digests

---

build.gradle
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/stash/client/StashClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

- okhttp requires posts to not have an empty body, so existing @POST methods were modified to accommodate this.
- okhttp mock server method changed from .play() to .start()

bump spinnaker dependencies

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParser.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParserTest.groovy

This adds support for [packagecloud uploads](https://docs.travis-ci.com/user/deployment/packagecloud).

Travis - Add support for packagecloud uploads

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/EmptyObject.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/GithubAuth.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

The new version of okhttp does not allow empty bodies on POST requests.
These changes makes the travis integration work again.

Travis integration fixes for dealing with new version of okhttp

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericParameterDefinition.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/service/BuildService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Config.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/RepoRequest.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/model/ConfigSpec.groovy

This adds parameterDefinitionList to the getJobConfig endpoint so that the `Job Parameters` field in deck for setting up triggers gets populated based on the travis job configuration.
Also the triggering for travis builds now takes a map of requestParams and overrides env config in the travis build when triggering.

Travis support overriding environment variables when triggering builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/health/PollingMonitorHealth.groovy

in groovy, ${ value } within single quotes don't get evaluated, this PR renders the names of the pollers correctly in the health check

fix poller names in health check

---

igor-web/igor-web.gradle

This change will fix problems where logrotate ignores
/etc/logrotate.d/igor due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)

Update logrotate file permissions

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

there are some issues with clouddriver flakiness so we will assume instead that an image that exists is there forever.

don't remove images in docker registry

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Config.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/model/ConfigSpec.groovy

The travis api acts strange when we trigger builds. We need to inject one property in `env` to be able to override `global_env`. We have to override `global_env` to override multiple properties in one job, if we do that in `env` it will trigger a job in travis for every property as a build matrix. The data inside `config.global_env` can both include strings and secrets `"MYPROPERTY=foo"` and secrets in a map like `{"secure":"xyz"}`. The code in this PR gathers the secrets from the last build and injects them into the payload when we trigger builds with igor against travis.

Travis - make igor able to override multiple properties in build

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy

- Updated to use masters/{name:.+} to handle names like jenkins.net

Handle "." in request parameter

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericBuild.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/TravisBuildState.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Branch.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Builds.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Commit.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Repository.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisBuildConverter.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverter.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisResultConverterSpec.groovy

With the old implementation we could miss build events when the same repository was built several times in parallel. This happens a lot in travis, ie you push to a branch and travis builds the branch and the PR at the same time.

Rewrite of travis build monitor to support concurrent builds.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

This makes travis properties available when you trigger based on specific branches.

Travis - make property parsing work on branches

---

README.md
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/BitBucketConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/BitBucketProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/ScmInfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/CommitController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/BitBucketClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/BitBucketMaster.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/AbstractBitBucketResponse.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/Author.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/Commit.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/CompareCommitsResponse.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/User.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/ScmInfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/bitbucket/CommitControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/BitBucketClientSpec.groovy

PR's are being opened against Deck, Echo, and Gate.
BitBucket Server (a.k.a. Stash) support already exists. This adds BitBucket Cloud support of pipeline triggers based on BitBucket webhooks and provides Orca the ability to retrieve a list of commits from BitBucket as part of it's GetCommits stage.

Add BitBucket Cloud support

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/logparser/PropertyParser.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/logparser/PropertyParserTest.groovy

This PR allows to extract multiple properties from the Travis log. The properties are printed in one line in the Travis log in JSON format and prepended by `SPINNAKER_CONFIG_JSON=`.
Something like this:
```
SPINNAKER_CONFIG_JSON={"key1": "value1", "key2": "value2", "key3": {"key3_1": "value3_1", "key3_2": "value3_2"} }
```
As a side note: I'm swallowing the exception in case the JSON is malformed - doing it in a similar fashion as the [Jenkins implementation](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy#L224). Possibily the exception should be handled differently, but that means changing Orca as well - shall be addressed in a different PR.

Parse a full JSON line from travis logs based on a magic string

---

igor-web/config/igor.yml
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/ArtifactDetailsDecorator.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/ConfigurableFileDecorator.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/DebDetailsDecorator.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/RpmDetailsDecorator.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericArtifact.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/service/ArtifactDecorator.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/ConfigurableFileDecoratorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/DebDetailsDecoratorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/RpmDetailsDecoratorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/service/ArtifactDecoratorSpec.groovy

This PR moves the knowledge of rpm and deb packages out of orca and into igor.
Artifact decoration can be feature toggled on and off at will.
The code here is not done yet, but the skeleton and most of the logic is present.
Currently this code only decorates rpm and deb packages. The design should make
it easy to add support for more package types/formats. Also I plan to add a parser
that can be configured through igor.yml. This would make it possible to add support
for new types of artifacts without touching the codebase in igor.
Please provide feedback on this both on the implementation and if this fits better
in orca.
There has been some concerns about property file handling. I think this PR keeps all
current functionality in igor intact.
spinnaker/spinnaker#1348

Decorate artifacts in igor.

---

README.md
igor-web/config/igor.yml
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParser.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParserTest.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

travis: configurable regexes to parse artifacts
Offer configurable regexes to find RPM/DEB artifacts pushed to
artifactory as the default ones only match on the output of the "art"
CLI, but wouldn't on that of any other tools.  The result is a failed
Spinnaker pipeline when no artifact is found.
With this change users may add a list of arbitrary regexes that will be
used to parse build logs.  An example is provided that corresponds to
Gradle maven-publish, which would match on the following line (taken
from a real build, with project names changed):
Upload https://artifacts.my.org/artifactory/yum-local/some/project/package-0.1.0.20161216.g1b1c767.rpm

feat(config/travis): configurable regexes to parse artifacts

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

The travis pro api does not have log_id in the api response for jobs. This means we need to find the logs slightly different.
Travis has three products Open source, Pro and Enterprise, they all behave a little bit different.
@abrahamoshel can you test that this works for you?

feat(travis/pro) Support fetching of logs from travis pro

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

- Removed the use of parallelStream while processing builds
- parallelStream may lead to a concurrency issue with redis read/write for close enough builds

fix(jenkins): Fixing missed build events on concurrent builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

- Uses a job's last build timestamp and sets the lower bound for the interval in Redis
- Uses a sliding upperbound as new builds appear on subsequent polls
- Ensures only one event gets fired for a completed build

fix(jenkins): Changing jenkins monitor algorithm to process builds using timestamp ranges

---

build.gradle

The generic exception handling from `kork-web` will now:
- include supplied exception messages in error responses
- propagate an underlying retrofit error's http status instead of http 500

chore(dependencies): Bump spinnaker-dependencies to 0.103.0

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/ScmInfoController.groovy

A first, very small step towards cleaning up Spinnaker's overall logging story. Aim of this PR is just to tune down the amount of disproportionate noise igor generates into our ES cluster. I'm happy to straight up delete some of these messages, too.
Example of our ElasticSearch log lines over 15 minutes as it is today:
@spinnaker/reviewers PTAL

chore(logs): Adjusting log levels to reduce noise

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy

Adding the ability to turn off jenkins polling. Its now possible to run multiple igors without duplicate notifications to echo.
Best viewed without whitespace changes (however, line commenting is not possible)
https://github.com/armory-io/igor/pull/1/files?w=1 
- polling is on by default
- igor's api still servers the jenkins info
- no jenkins events are sent to echo
- any changes in jenkins does not persist to cache
- there must be at least 1 polling igor to kick off jobs.

feat(jenkins) allow polling to be turned off

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Commit.groovy

This adds committer and compare url to the scm info when available in travis builds. This is the first step of making the pipeline in ui contain more relevant info for each pipeline execution.
```
{
"building":false,
"name":"org/repo",
"number":610,
"duration":626,
"timestamp":"1503563992000",
"result":"SUCCESS",
"artifacts":[],
"url":"https://travis.xxx.yy/org/repo/builds/1778996",
"scm":[
{
"branch":"master",
"name":"master",
"sha1":"7bd574b5a2eea9d6d3ddc41d26cfc0a7cb1bc7e1",
"committer":"Gard Rimestad",
"compareUrl":"https://github.com/org/repo/compare/939543bcee5b328012b869adb639f2df5c6f18ca...7bd574b5a2eea9d6d3ddc41d26cfc0a7cb1bc7e1"
}
]
}
```
Ping @anotherchrisberry

feat(travis/commit_info) Add committer and compareUrl to the build status

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/Commit.groovy

This adds the commit message to the scm payload for travis builds.
The reason we do this is that we want to surface this information committer, sha1, link to diff and commit message in the UI.

feat(travis/commit_info) Add commit message to the scm payload

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy

* improve logging of triggering and getting triggered builds
The current implementation generates a queueId using the timestamp to seconds. It has a check if the queued item already exists, but I believe it can still produce race conditions.

fix(travis/triggerBuild) Use request id given by travis for queue id.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildCacheSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

* Track running and finished travis builds in separate caches
* Migrate old buildCache to new format (so we don't push redundant build events)
* Keep updating the old cache to support rollback
This change enable us to have more consistent trigger behaviour for repositories that
has many concurrent builds.
Old implementation:
```
buildNumber | state     | event
1           | running   | pushes build started event
2           | running   | pushes build started event
1           | finished  | none
2           | finished  | pushes build finished event
```
New implementation:
```
buildNumber | state     | event
1           | running   | pushes build started event
2           | running   | pushes build started event
1           | finished  | pushes build finished event
2           | finished  | …
```

feat(travis): New caching strategy for builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy

- When turned on, builds older than `lookBackWindowMins` will not be processed
- offsetting that with the polling interval

feat(jenkins): Adding a configurable lookBack window, off by default

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy

Saw an error where the scm information was not pulled from jenkins during a pipeline. A re-run of the pipeline fixed this. I think adding a retry for this call to handle any jenkins blips might solve the problem. 
Thoughts? @jeyrschabu @robzienert

fix(jenkins): adding retry for gitDetails

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/NoDiscoveryApplicationStatusPublisher.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DiscoveryPollingConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/PollingMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy

When running igor with Discovery & Dynomite enabled at the same time, we run into a pretty awesome cycle:
```
buildCache defined in URL [jar:file:/BuildCache.class]
┌─────┐
|  dynomiteClientDelegate defined in class path resource [DynomiteConfig.class]
↑     ↓
|  dynoJedisClient defined in class path resource [DynomiteConfig.class]
↑     ↓
|  discoveryClient defined in class path resource [EurekaComponents.class]
↑     ↓
|  optionalArgs defined in class path resource [EurekaComponents.class]
↑     ↓
|  healthCheckHandler defined in class path resource [EurekaComponents.class]
↑     ↓
|  pollingMonitorHealth (field private PollingMonitorHealth.pollers)
↑     ↓
|  dockerMonitor (field private DockerMonitor.cache)
↑     ↓
|  dockerRegistryCache defined in URL …
```

fix(discovery): Fixing cyclic dependency issue on startup when discovery client avail

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy

This PR fixes https://github.com/spinnaker/spinnaker/issues/2166.
The basic idea is to reduce the code duplication by using [template method design pattern](https://en.wikipedia.org/wiki/Template_method_pattern). All the common code is pushed to `CommonPollingMonitor`.

refactor(core): Reduce code duplication in polling monitors

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

There is a bug in the current code where running builds only emits events if the branch is known to igor from one finished build. This will fix that and also simplify the code.

fix(travis) emmit build started events for new branches as well

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy

The migration code path has been active since May 2016.
Users that are using travis and have not updated igor since May 2016 will get redundant triggers and empty job lists. I do not think this will hit many users.

refactor(travis/cache): Remove migration to cache with ttl set

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

* Explicit tracking of each running build igor sees.
- travis api does not allways populate latest_build as one would expect.
* Removing some compiler warnings on cache classes
* Fixing the trigger logic on repo level triggers

fix(travis/triggers): Keep track of builds in flight.

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy

Turns out Spring has trouble autowiring beans that aren't declared.

fix(jenkins): include retrySupport bean

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy

Trying to trace through the original issue that caused us to add this retry logic. Probably should have included some logging in the first place.
cc @ajordens

feat(jenkins): add log message when artifact cannot be found

---

igor-web/etc/init/igor.conf

Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.

fix(igor/log): Append to log instead of overwrite

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/TravisConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/TravisClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Job.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/V3Log.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

This is needed for filtering build events based on artifacts. Depends on an upcoming change in echo.
Kind of a duplicate of #132, but this change will only query Travis for artifacts for completed builds, and only once per event.

feat(travis): Include artifacts in build event for completed builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryKeyFactory.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryKeyFormatException.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryV1Key.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryV2Key.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigrationSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryKeyFactorySpec.groovy

Updates redis key format from v1 to v2 for docker registry cache, which removes the docker repository url from the key.

feat(docker): Redis key migration

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java

This is a nice log message, except that it's like the worst log message.

chore(docker): Removing totally unreasonable log statement

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

break processProjectsOfMaster into multiple functions to make it
more readable and decrease indentation levels
use early exits when possible
make things private when possible
don't explicitly build the list of jobs too old to include only to
exclude it from the main list (side effect: no longer debug logging
them)
things should otherwise work in the same way

refactor(jenkins): mostly cosmetic changes

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/CommitController.groovy

Throwing a `RuntimeException` will cause the service to behave as it does today, but we'll avoid an NPE on L78.

fix(bitbucket): Fix NPE caused by non-network retrofit errors

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/PollContext.java

The fastforward flag was being set incorrectly, and thresholds were not influencing changing its value.

fix(polling): Fast-forward flag correctly influencing send events

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/admin/AdminController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/admin/AdminControllerSpec.groovy

Currently igor fails on startup when there are no active CI accounts,
due to a spring dependency error.

fix(polling): Fix igor startup with no active ci accounts

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/client/DefaultJenkinsRetrofitRequestInterceptorProvider.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/client/JenkinsRetrofitRequestInterceptorProvider.java

Allows customization of the Jenkins request interceptor for http calls.
Makes username/password non manditory on jenkins host configuration.
Example use case would be x509 authentication in Jenkins where the identity
is extracted from the client certificate instead of an HTTP request header.

feat(jenkins): extension point for http request interceptor

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy

#241 lead to Travis and Gitlab no longer sending events when they should (and sending events when they should not). Also, the send event flag was ignored for Jenkins; this commit also fixes that.
FYI @robzienert

fix(polling): Regression causes send event logic to be inverted

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryProperties.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy

Make it possible to set an `itemUpperThreshold` property for the Docker Registry poller in Igor, that will function as a fallback value if the Docker registries retrieved from Clouddriver does not have this value set.
@robzienert PTAL

feat(docker): Fallback value for item circuit breaker in Docker poller

---

igor-web/config/igor.yml
igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy

I've been getting a lot of questions about igor's new build index safeguard functionality. This feature was introduced to help guard against accidental re-indexing of build indexes (and potentially running pipelines against old code). 
This PR changes the default value from default-safe to default-basically-disabled.
Having initially launched this feature with a default-safe value, I've realized it's hard for people to upgrade to surprises, and frustrating for people who are in early adoption phase. For organizations that have Spinnaker operations stable, however, this is a setting that you'll want to use and right-size.
By right-sizing the `spinnaker.pollingSafeguard.itemUpperThreshold` to the number of new builds ~every 60 seconds (plus headroom), you can help prevent bad data (from …

refactor(safeguard): Setting default high value on item threshold

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

#257 (that was supposed to fix a regression in #255) caused the Docker Monitor to never initialize.
Revert to using `ConditionalOnProperty` instead.
@ezimanyi @robzienert PTAL

fix(docker): Fix igor startup with dockerRegistry enabled

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCache.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigration.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryV2Key.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerRegistryCacheV2KeysMigrationSpec.groovy

The migrator was happily converting V2 keys as well, reading `account` as `v2` and then constructing a new key like `prefix:id:v2:v2:registry:tag`
Proof in the form of a failing test:
```
22:07:51.730 [main] DEBUG com.netflix.spinnaker.igor.docker.DockerRegistryCacheV2KeysMigration - Starting migration
22:07:51.733 [main] INFO com.netflix.spinnaker.igor.docker.DockerRegistryCacheV2KeysMigration - Migrated 4 v1 keys in 3ms
Condition not satisfied:
jedis.keys("igor:*:v2:*") == [ "igor:totalInvalid:v2:acct:registry:tag", "igor:dockerRegistry:v2:acct:registry:tag" ] as Set
|     |                   |
|     |                   false
|     [igor:dockerRegistry:v2:v2:acct:tag, igor:totalInvalid:v2:acct:registry:tag, igor:dockerRegistry:v2:acct:registry:tag]
redis.clients.jedis.Jedis@49b2a47d …
```

fix(docker): Redis key migration: Only migrate V1 keys

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/travis/service/TravisService.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

The code was always _supposed_ to fetch logs in this code path. However, due to a bug in the JSON to Groovy deserialization, the field containing job id's was always null. Due to groovy's nature, this just caused Igor to not fetch any logs, instead of failing.
I fixed the issue (in #223), but then realized that the log fetching made the code way slower in places where we didn't really need artifacts. So I've disabled logs/artifacts fetching from everywhere but the TravisBuildMonitor.

fix(travis): Fix a regression that cause getBuilds() to be very slow

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParser.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParserTest.groovy

The test that covers packagecloud did not actually validate that the artifact was identified.
This fixes both the test and the regex.

fix(travis/packagecloud): Fix escaping in the packagecloud regex

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

I believe this should be an error message. For example, docker: if the delta goes above the limit, then you won't get any more new build triggers with docker.

fix(safeguards) exceeding upper poll threshold messages are errors

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/stash/CommitController.groovy

Previously we would swallow the exception and NPE.
Now we report an error and return an empty list.

fix(web): Log an error when commits cannot be fetched from stash

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsProperties.groovy

As of Spring Boot 1.5, `@ConfigurationProperties` classes that use constraint annotations should also be annotated with `@Validated`; this is currently throwing warnings but may actually break in the future.

fix(build): Fix spring warnings about validated classes

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/ScmDetails.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

- Some jenkins jobs will trigger with multiple scms, this however caused igor to break and not return any scm information
- Jenkins XML api requires remoteUrl to be pluralized

fix(jenkins) return multiple scms when jenkins has multiple scms and remoteUrl calls

---

README.md
build.gradle

Starting igor with ./gradlew -DDEBUG=true now causes the JVM to listen on port 8188 for a remote debugger.

chore(build): Add debug flag to igor build

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy

- set `networkaddress.cache.ttl=0`

fix(*): Tell JVM to not cache DNS results internally

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy

- mark events as posted only when they were posted successfully

fix(jenkins): Only mark event as posted on successful response from echo

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

Igor fails to start when the artifact decorator is not enabled. This change makes the decorator optional.
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 5 of method travisMasters in com.netflix.spinnaker.igor.config.TravisConfig required a bean of type 'com.netflix.spinnaker.igor.service.ArtifactDecorator' that could not be found.
```

fix(travis): Make artifact decorator optional

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/RpmDetailsDecorator.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/artifact/decorator/RpmDetailsDecoratorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/service/ArtifactDecoratorSpec.groovy

Make the rpm decorator produce the proper version for rpms.

fix(artifacts/rpm): the generated version should be complete

---

igor-web/config/igor.yml
igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java

The travis api needs some time after a build is finished in order to have
the build data present in the apis.
This is configurable through `travis.newBuildGracePeriod`

fix(travis): grace period before triggering with new travis builds

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/QueuedJob.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

We don't want to throw an NPE if there is no `executable` element in the
response. I noticed this element now seems to correspond to `id` so use
that as a fallback if we can.

fix(jenkins): don't error out on queue item responses with missing field

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/QueuedJob.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

Orca runs MonitorQueuedJenkinsJobTask until the number is not null and
then uses that in MonitorJenkinsJobTask. Returning the id in QueuedJob
results in the wrong number stored in the context and MonitorJenkinsJobTask
then gets 404s back from Jenkins.

fix(jenkins): don't mistake the queue id for the job number

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy

We currently don't update the docker image cache when either the prior or the current digest is null. This means that any tag that was present before trackDigests was enabled will always have its digest set to null. Change this so we do set the digest any time the new one is not null.
In order to avoid triggering multiple pipelines when turning trackDigests on, we won't send an event to echo when updating from a null to non-null digest (as we don't actually know if it was updated), we'll only update the cache.

 fix(docker): Update cache when a null tag becomes non-null

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/ParameterDefinition.java

Some Jenkins parameter types (e.g. git parameters, it's a thing, promise) do not have the `<defaultParameterValue>`, so these defaults blow up.

fix(jenkins): guard against NPE on parameter definitions

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy

Add `Spinnaker-igor` for User-Agent header to all requests to Jenkins
following the convention in clouddriver.

fix(jenkins): Add Spinnaker user-agent string to Jenkins requests

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsProperties.groovy

```
jenkins:
masters:
-
address: "https://jenkins.com"
name: spinnaker
trustStore: "*"
```
or:
```
jenkins:
masters:
-
address: "https://jenkins.com"
name: spinnaker
trustStore: /path/to/truststore.p12
trustStoreType: PKCS12
trustStorePassword: my_truststore_password
```

feat(jenkins): Support for overriding TrustStore used by Jenkins clients

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/ScmDetails.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

The jenkins-git plugin is removing the BuildData structure from the results of the build as of version 4.0.0 of the plugin. Spinnaker uses that data to populate the 'scm' information for the build, so users who have upgraded their jenkins-git plugin are not getting any SCM information in Spinnaker.
The replacement for BuildData is a new structure BuildDetails. All of the information we were fetching from BuildData is available in BuildDetails.
Update igor to look for the SCM information in BuildDetails if nothing is found in BuildData. This change is backwards-compatible as the new BuildDetails location is only queried if there is nothing in the old BuildData location.
Closes spinnaker/spinnaker#3927

fix(jenkins): Use new location for revision information

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

* Also rolled back a visibility change to CommonPollingMonitor.worker so it is accessible in Spock tests that assign it as a property

fix(tests): Use JUnit vintage engine so Spock tests still run

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericArtifact.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/BuildArtifact.groovy

This is an alternative to the original PR adding support for expected artifact matchable Jenkins artifacts reverted in https://github.com/spinnaker/igor/pull/398.
This approach defers the addition of additional fields to Jenkins artifacts to the point where echo retrieves additional build details. Since it doesn't involve any changes to API access to Jenkins, there should be no performance implications for large Jenkins masters.
Like the original PR, the additional data elements on Jenkins artifacts are strictly additive, so should have no impact on existing code referring to `displayName`, `relativePath`, etc.
cc / @robzienert @eleftherias @Jammy-Louie

feat(jenkins): Expected artifact matchable Jenkins artifacts

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ConcourseClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/SkyService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java
igor-web/src/test/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitorTest.java

See https://github.com/concourse/concourse/issues/3558.
Concourse does not correctly produce a 401 when a token is invalid/expires when executing commands to retrieve teams and pipelines.
Calls to `/sky/userinfo` do return a 401 on invalid/expired token, so as a workaround we preface calls to resource listings with a call to `/sky/userinfo`.

fix(concourse): Detect Concourse token expiry

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericBuild.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java

Returning a `GenericBuild` now which properly supports listing builds available for manual execution:

fix(concourse): Tweak return type to support manual execution build listing

---

igor-web/src/main/java/com/netflix/spinnaker/igor/artifacts/ArtifactController.java

This allows version to be something like `1.4.0-h40.5222222` and for that whole string to come through.

fix(artifacts): fixed parsing of version

---

igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/CloudBuildFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepository.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCredentialService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepositoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutorTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/WireMockConfig.java
igor-web/src/test/resources/gcb/gcb-test-account.json
igor-web/src/test/resources/gcb/gcb-test.yml

This PR adds the groundwork necessary for configuring GCB accounts, and adds an endpoint for triggering a GCB build using a specified account. Functionality to look up the status of a build and get build results will come later.

feat(gcb): Add support for triggering GCB builds

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepository.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepositoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

The UI for the GCB stage should provide a drop-down that lists available accounts, so we need to support this operation on the back-end.
This is similar to the '/masters' endpoint that lists the available build services for other services. I didn't have GCB implement BuildService because the types of operations it supports are different, which means that we don't get the '/masters' functionality for free.
As I develop this functionality further I'll see whether there's a more general interface that emerges that this and other build services can implement, at which point we may be able to add these into the general
'/masters/ endpoint.  But for now, adding a separate '/gcb/accounts' endpoint that will list GCB accounts.

feat(gcb): Add endpoint for listing accounts

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/RepoRequest.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

Lets you customize the build message used when Spinnaker triggers builds in Travis. If you set a custom parameter in the Travis stage in Spinnaker with the key `travis.buildMessage` (customizable) (e.g `travis.buildMessage=My customized message`, the build message in Travis will be _Triggered from Spinnaker: My customized message_. The first part of this message is not possible to change.

feat(travis): Customize the Travis build message on triggered builds

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisCache.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/TravisClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Log.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

The Travis™ API often returns incomplete logs for a few moments (~30-60 seconds) after a build completes. As we are dependent on the logs for detecting both build artifacts and fetching properties, I've added additional checks that will cause Spinnaker to wait until the logs are ready before trying to parse them. If you thought that there's an endpoint in the Travis API to check if the logs are ready yet, you would be wrong. So we have to check this by actually downloading the logs multiple times until they are complete.
**Pros:** We get rid of a whole bunch of weird, non-deterministic bugs caused by the last few lines of the log to sometimes be cut away. Especially since the last couple of lines is where users usually upload artifacts, our pipelines will now Work More Often™ and Fail …

fix(travis): Check that logs are complete before parsing them

---

igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitorSpec.groovy

When the context root is non-empty, the Artifactory client constructs a post request with an extra slash in the path, which in turn causes Artifactory to throw a spurious error about a missing repo key.
```
POST /artifactory//api/search/aql
```

 fix(artifactory): Avoid AQL 500 when context root is non-empty

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildCache.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParser.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildStatus.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildCacheSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParserSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildStatusSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTestConfig.java
igor-web/src/test/resources/gcb/gcb-test.yml

* fix(gcb): Fix deserialization of Build object 
Jackson's ObjectMapper does not properly deserialize Build objects, as nested properties that extend com.google.api.client.json.GenericJson
(which itself implements Map) are are deserialized as Maps rather than as the specific type.
There is probably a way of configuring ObjectMapper to do this properly but I have not (yet) been able to find it. As a workaround, use the Google Cloud supported deserialization classes to deserialize this JSON. In order to keep this workaround localized, make a small class that will handle deserializing Build classes.
This commit also adds BuildOptions to the build in the integration test; adding this causes the test to fail when using the standard ObjectMapper for deserialization.
* feat(gcb): Add endpoints …

feat(gcb): Add endpoints for storing and retrieving build status

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/Event.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/Plan.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java

Put resource ids are buried under two further levels of nesting than get resources:

fix(concourse): Fix deserialization of put resource metadata

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy

In the Spring Boot 2 upgrade, `spring.config.location` overrides all other config locations. The equivalent property is now called `spring.config.additional-location`.
This fix allows the app the to run without additional config files.

fix(core): Spring does not override default configuration files.

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildCache.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParser.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildStatus.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutorTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParserSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

* style(gcb): Change indent to 2 spaces 
The default for igor was recently changed to 2 spaces to match our other microservices; update the 2 gcb files that still have 4-space indents. This commit is whitespace-only.
* refactor(gcb): Extract all interactions with GCB API to a client class 
Currently GoogleCloudBuildAccount directly generates calls to the GCB API (though uses a GoogleCloudBuildExecutor to actually execute the requests). As we add more complex logic to GoogleCloudBuildAccount and want to add some unit tests, it makes sense to pull the logic that is just generating API calls into a separate class so it can be easily stubbed.
Create a GoogleCloudBuildClient which will expose GCB API operations and execute them for the consumer.
* refactor(gcb): Standardize return values in …

 feat(gcb): Add ttl to build cache entries and fall back to polling

---

build.gradle
igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/CloudBuildFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifactFetcher.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/model/GoogleCloudBuildArtifact.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/model/GoogleCloudStorageObject.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifactFetcherSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/model/GoogleCloudStorageObjectSpec.groovy

* feat(gcb): Add support for parsing GCS paths 
In order to fetch the list of artifacts produced by a build, we'll need to fetch the manifest from GCS. This will involve translating a GCS path into a bucket/object/version, which there is no helper function in the GCS library for; write a small class to do this and test it.
* feat(gcb): Add GCS object to GCB account 
As Google Cloud Build stores a manifest of produced artifacts in Google Cloud Storage, a GCB account will need to be able to talk to GCS in order to return information about produced artifacts.
This allows us to better encapsulate information about produced artifacts rather than having the GCB account simply return a path to the manfest and require the caller to parse any artifacts (which are in a GCB-specific format).
* …

feat(gcb): Add endpoint to fetch build artifacts

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

In order to allow users to filter their builds to those started by Spinnaker, add a tag to builds that are started.

feat(gcb): Add tag to builds triggered by Spinnaker

---

igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryItem.java
igor-web/src/test/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryItemTest.java

Previously we got the base URL from the client which unintuitively removed the context root for us. Now we grab it from the search which has the Artifactory base URLs that Igor is configured with.
We also provide a more specific URL that identifies a particular pom, rather than just the directory of the group, artifact, and version.

fix(artifactory): correctly construct Artifactory URL

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy

Spring Boot 2 tightened up restrictions, but CI job names may legitimately include encoded slashes
See https://github.com/spinnaker/spinnaker/issues/4477
https://spinnakerteam.slack.com/archives/C091CCWRJ/p1559269913055000

fix(boot2): Allow paths with URL-encoded slashes

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifactFetcher.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifactFetcherSpec.groovy

The logic to fetch an artifact manifest does not properly account for the GCS path containing a version (as in gs://bucket/file.json#123).
This isn't causing any active issues as GCB creates a file named with a UUID and does not include the version in the build output, but we should properly handle this in case this changes (or in case we re-use the artifact fetching code elsewhere).

fix(gcb): Correctly fetch artifact manifest when it contains a version

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/model/GenericGitRevision.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/service/GitlabCiService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/service/BuildOperations.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/service/BuildProperties.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerService.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/TravisClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/Root.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Commit.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Log.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisBuildConverter.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java

Travis added a new property in version 2.2.9 (also available on travis-ci.org) that tells us if the log is complete or not. This allows us to be more efficient in the way we fetch artifacts and properties from Travis. It is not backwards compatible, so we have to keep the old way of doing it around for a while.
Each Travis master will be queried at Igor startup for some simple feature detection to determine wether to use the legacy method or the new method.
A few interfaces has been changed to use GenericBuild instead of `buildNumber`. This allows for some reduction in complexity for a few of the providers that don't use `buildNumber` internally, as we don't have to query the master for `buildId` multiple times.
Also contains some spring cleaning of the TravisClient and the TravisService, …

feat(travis): Support for log_complete from Travis API

---

build.gradle
igor-bom/igor-bom.gradle

compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa

fix(bom): Fix generated pom.xml to omit invalid lombok declaration

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java

This makes it possible to manually trigger pipelines on tag builds
again.

fix(travis): List tag builds from travis

---

build.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/model/Commit.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/health/PollingMonitorHealth.java

testing some upcoming refactorings in kork, found a usage of joda-time that
came as a transitive dependency from somewhere, replaced usage with java.time

chore(cleanup): minor dependency cleanup

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/NexusConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/NexusProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusEventPoster.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/model/NexusAssetEvent.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/model/NexusAssetWebhookPayload.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/model/NexusRepo.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/model/NexusRepositoryType.java
igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java

Nexus does not provide the same querying functionality that Artifactory does. We can't use the same timestamp trick in AQL for polling the latest artifacts, but we can configure a webhook in Nexus to notify of new assets. This commit adds that webhook endpoint in Igor so that Nexus can notify Igor of new assets which will send the new artifact to echo.

feat(nexus): add Nexus webhook for artifact triggering

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy

Follow-up to  #454
Before:
```
$ curl localhost:8088/jobs/master/%25
{"timestamp":"2019-08-31T01:45:37.293+0000","status":500,"error":"Internal Server Error","message":"The request was rejected because the URL contained a potentially malicious String \"%25\""}%
```
After:
```
$ curl localhost:8088/jobs/master/%25
{"timestamp":"2019-08-31T01:46:30.379+0000","status":404,"error":"Not Found","message":"Master 'master' does not exist"}%
```
As previously noted, we don't seem to have any existing tests that make actual requests that route through `StrictFirewall`.

fix(boot2): Allow url-encoded % in URLs

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

In Jenkins, you can have a "dynamic choice parameter". This means that you can write a script to generate all the dropdown choices for a parameter. It seems like this script is only run when you hit "build with parameters". When you query for the job config (`https://jenkins-controller/job/job-name//api/xml?exclude=/*/action&exclude=/*/build&exclude=/*/property[not(parameterDefinition)]`) you actually get no choices. Better yet, instead of an empty list, `choices` is null!
This PR makes adds a null check to `parameterDefinition.choices` so that if it's `null` we just don't validate. Right now we throw an `NPE`.

fix(jenkins): don't npe on dynamic choice parameters

---

igor-web/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/Config.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/client/model/v3/ConfigSpec.groovy

When the `config` section is returned as part of a *build* (which is unsupported in the Travis v3 API), `global_env` is a list of Strings. When it is returned as part of a *job*, `global_env` is instead a space separated String. And since env variable values can also contain spaces and equal signs, I had to create a little regex parser thingy.
This also fixes an issue in Deck where you can't add parameters to a Travis stage if `.travis.yml` contains anything in the `env.global` section.

fix(travis): Correctly parse global_env from Travis v3 API

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/NexusProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/nexus/NexusEventPoster.java
igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java

Originally I used “repos” to list Nexus repos. Artifactory uses “searches”. I used “repo” instead at first because Nexus actually pushes rather than the polling search that Artifactory does.  But it seems like it is best to stay consistent with Artifactory config naming, and the underlying implementation doesn’t really matter. Though they will function a bit differently. Also, there is a lot of Hal code that could be shared if the naming was consistent. This change makes the naming consistent.

fix(nexus): change Nexus config

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitor.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java

This migrator has been in place since October 2017, and is no longer needed. Also it was a bit misleading. The `initialize` name suggests it is run on bean creation, but it actually ran every polling cycle, which seems a bit excess for a migrator. Since it was only used by the Travis integration, I just removed the whole thing.

chore(travis): Remove old build cache migrator

---

igor-web/igor-web.gradle

Adding gradle dependency for new kork-secrets-gcp module.
PR introducing GcsSecretsEngine: spinnaker/kork#380
Linked issue: spinnaker/spinnaker#4668

feat(secrets/gcs): Support for decrypting spinnaker secrets in GCS

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java

Builds should be added to cache correctly now and the admin fastforward command should work
It solves https://github.com/spinnaker/spinnaker/issues/5047
I ran into this problem because we had over 1000 builds on our concourse instance, so we were running into `cache exceeds upper threshold (1000)`.
Upon trying to fix this, I realized the builds were never being compared to what was in the cache until the commitDelta function, which unfortunately we don't get to unless the threshold is less than 1000.  
Note: This is my first PR to a spinnaker project and my first time coding in java so open to any and all suggestions!

fix(concourse): Fix caching of concourse build events

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/InfoController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/model/BuildServiceProvider.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy

Added permissioning to Google Cloud Build accounts.  
It solves https://github.com/spinnaker/spinnaker/issues/4814
Protects the gcb accounts so that only defined roles can READ and WRITE.
- To be able to configure a pipeline with the gcb account, you need READ permissions.
- To be able to submit a CloudBuild job using the account, you need WRITE permissions.

feat(gcb): Add permissioning to Google Cloud Build accounts

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/IgorConfigurationProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/config/IgorRetrofitConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/KeelConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/keel/KeelService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy

In order to react to new docker containers in `keel` we need to know when there are new containers. This PR adds functionality to emit events to `keel` with the same criteria as sending new events to echo. 
This won't kick in unless you have keel enabled. The format for the docker event we send is subject to change, but I think this is a decent first start 🤷‍♀ we shall see.

feat(keel): send keel docker events if enabled

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

This is one way to fix https://github.com/spinnaker/spinnaker/issues/5055
Another way is to just throw the exception without adding retry logic so that the retry logic belongs in Orca. However I noticed that the other operation `getArtifactPathFromBuild` already has a retry logic so I am going with this approach for consistency.
This PR add automatic retry logic to Jenkins' `getPropertyFile` similar to `getGitDetails` (sans Hystrix command).
Before this PR, if Jenkins return transient failure on `getPropertyFile` it will not retried and the Jenkins stage will immediately fail. User will have to restart the stage just to get the build artifact.
After this PR, Igor will retry up to 5 times with 2 seconds non-exponential backoff if Jenkins return 5xx code.

feat(jenkins): Add retry logic on getting build artifact

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java

Added ability to call existing GCB triggers.
This is part of: https://github.com/spinnaker/spinnaker/issues/5076
Added two new endpoints to `igor` to:
* List existing triggers available for the gcb account.
* Call a trigger given its id. 
Calling a trigger will return a Build object, which then can be used to monitor the build using the existing functionality in `orca`.

feat(gcb): Allow invoking existing GCB triggers

---

igor-web/src/test/java/com/netflix/spinnaker/igor/artifacts/TestArtifactService.java

The all-arg and no-arg constructors for Artifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.

refactor(artifacts): Use builder to create artifacts

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitorSpec.groovy

This fix addresses a validation failure in kork when a polling agent tries to acquire a lock using the lockService. This issue can be reproduced by enabling Artifactory build trigger for maven artifacts. The search configuration looks like 
```
searches:
- name: test-maven
permissions: {}
baseUrl: https://artifactory-url/artifactory
repo: test-maven-local
groupId: com.mycompany
username:
```
The Artifactory polling logic fails with the following exception:
```
Caused by: com.netflix.spinnaker.kork.exceptions.ConstraintViolationException: Lock name must be alphanumeric, may contain dots
at com.netflix.spinnaker.kork.lock.LockManager$LockOptions.validateInputs(LockManager.java:315
```
The class CommonPollingMonitor initialises the lockName variable as
```
final String lockName = …
```

fix(ArtifactoryPollingMonitor): Fix failing validation on lockName

---

Dockerfile.java8
Dockerfile.slim
Dockerfile.ubuntu-java8

Part of the [Java 11 migration effort](https://github.com/spinnaker/community/blob/master/rfc/java11.md).

chore(java11): Switch the default containers to use Java 11.

---

igor-web/igor-web.gradle

In Java 8, this is included, but the Java 11 JRE doesn't include it, so
we need to bundle it with Spinnaker.

chore(jaxb): explicitly add JAXB to the classpath

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/CloudBuildFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepository.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifact.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildArtifactFetcher.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildCache.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildParser.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildStatus.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudStorageObject.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCredentialsService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/NonnullByDefault.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/package-info.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepositoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTestConfig.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudStorageObjectSpec.groovy

* refactor(gcb): Move all GCB files into the same package 
The GoolgeCloudBuildArtifact and GoolgeCloudBuildConfig classes were in different packages; by moving these to the same package as the other GCB classes we'll be able to reduce the visibility of many GCB classes to package-private.
* refactor(gcb): Make packages package-private and final where possible 
The only external contract the com.netflix.spinnaker.igor.gcb package intends to provide is the GoogleCloudBuildController component; everything else is an implementation detail.
To better communicate and enforce this:
* Make the controller (and all mapped methods) public; some of these were package-private before which works because Spring uses reflection to call controllers, but we should document them accurately as being called …

refactor(gcb): Reduce visibility of GCB packages

---

igor-web/src/main/java/com/netflix/spinnaker/igor/scm/ManagedDeliveryScmController.java

I noticed that the UI was not showing any helpful error information when we failed to retrieve the delivery config file from SCM, say due to missing permissions in Stash. This allows any error from stash to be returned to orca so it will show up on the UI.

fix(stash): Pass thru any HTTP errors from stash

---

igor-monitor-jenkins/src/main/java/com/netflix/spinnaker/igor/jenkins/JenkinsService.java
igor-monitor-jenkins/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsServiceSpec.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildEvent.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildEvent.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildEvent.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildEvent.java

Also fixed some compiler warnings.
Issue was that location headers from Jenkins include a final trailing `/`. Turns out Groovy's positional indexes on arrays are off-by-one from what Java is.

fix(jenkins): Parse build number from Location header correctly

---

Dockerfile.compile

Currently build are failing because of old files that exist in the cache

fix(build): Clean before building Docker container

---

igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccountSpec.groovy

Add a new API to get all projects for specific account and region. This API
iterates over all pages and aggregates the results. The number of projects
per region per account is at most 5000. Each page contains 100 results, so
at most 50 calls will be made to fetch all projects. I was thinking about
returning the nextToken to caller and let caller do pagination. However, I
found out that none of list* APIs igor provides supports pagination. Therefore
I decide to follow the pattern to return all results in one batch. It should
be fine since the number of projects is less than 100 in most cases.

feat(codebuild): Add API to list projects

---

igor-web/src/main/java/com/netflix/spinnaker/igor/codebuild/AwsCodeBuildAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/AwsCodeBuildConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/AwsCodeBuildProperties.java

After this change, user should be able to specify static credential for codebuild
and all codebuild accounts will use this credential to assume role. If assume role
is not present, the static credential itself will be used to call CodeBuild APIs.

feat(codebuild): Add support for static credentials

---

README.md
igor-web/config/igor.yml

https://github.com/spinnaker/spinnaker/issues/5459
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

docs(travis): Use travis-ci.com rather than travis-ci.org

---

igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildController.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java

Fixes spinnaker/spinnaker#5593
* test(gcb): Update tests to run postFilter logic
The GCB integration tests currently don't run the postFilter logic that is added as an annotation on controller methods. I believe this is because we've been to selective in exactly the beans that should be present in the test, and are not pulling in the required Spring Security beans.
In order to fix this, add the same @ComponentScan that we have on Main.class to the test so it pulls in the same beans.  (We can then also remove the specific controller bean we'd been pulling in, but will leave all the configuration beans in place.)
This causes the listAccountTest to fail because the listAccounts function is currently broken; the next commit will fix the function and the test.
* fix(gcb): Return mutable lists …

fix(gcb): Return mutable lists from methods annoated with PostFilter

---

igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

If you have builds that creates very large logs, the number of builds returned can cause issues or timeouts in the Travis API. Limiting the number of builds seems to mitigate the issue.
Drawbacks: This will limit the number of builds you'll see in the build drop down of a manual execution to 10 (but it won't affect the build monitor at all as it uses another endpoint).

fix(travis): Limit the number of returned builds

---

igor-core/src/main/java/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-monitor-artifactory/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-monitor-artifactory/src/test/groovy/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitorSpec.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitor.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/docker/DockerMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSchedulingSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitorSchedulingSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitorSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitorTest.java

It's not currently possible to start/stop `igor` from sending events of completed builds/newly published images to `echo`.
It is useful to have this functionality because igor should always be "polling" to have a local cache of "triggered" builds/images.
This change allows an operator to:
* have two clusters of `igor` both polling but only one sending events (i.e. triggering pipeline)
* switch which cluster is sending events without generating duplicate events/double triggering

fix(events): Add dynamic config service to send events

---

igor-core/src/main/java/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java

Follow up to feedback in https://github.com/spinnaker/igor/pull/724.
Renaming the property to `spinnaker.build.sendEventsEnabled`, this way it is symmetric to existing properties in `igor`, e.g.:
```yaml
spinnaker:
build:
pollingEnabled: true
sendEventsEnabled: false
```

fix(events): rename the send events prop

---

igor-core/src/main/java/com/netflix/spinnaker/igor/IgorConfigurationProperties.java
igor-monitor-plugins/igor-monitor-plugins.gradle
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginCache.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginsBuildMonitor.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/Front50Service.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginInfo.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseService.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginRequiresParser.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/model/PluginEvent.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/model/PluginRelease.java
igor-monitor-plugins/src/test/groovy/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseServiceSpec.groovy
igor-monitor-plugins/src/test/groovy/com/netflix/spinnaker/igor/plugins/front50/PluginRequiresParserSpec.groovy
igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/Front50Config.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java
settings.gradle

First step towards triggering pipelines off of new plugins. The initial implementation only supports looking at front50 as a plugin repository, but the storage schema supports future enhancements for PF4J's more general UpdateRepository format as well.

feat(monitor): Add plugins monitor

---

halconfig/README.md
halconfig/igor.yml
igor-web/config/igor.yml

The redis url is being set in the Halyard-specific file that is concatenated to the config; let's just move that defaulting to the base igor.yml.
This should not cause any visible change to non-Halyard users, as we are defaulting back to the same localhost:6379 if the redis override is not defined. It will also not affect Halyard users as it's just changing where we set this value for them.

config(core): Push Halyard config to base

---

igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/config/GoogleCloudBuildProperties.java
igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactory.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java

This commit moves the GoogleCloudBuildProperties.Account class to be immutable and use constructor binding. It also makes the minor change of storing the result of Permissions.build() instead of the raw builder, rather than calling Permissions.build() every time we ask for the permissions.
It also annotates the class as NonnullByDefault, and handles any necessary null defaulting in the constructor.

refactor(gcb): Make GCB account immutable and null-safe

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

Fix for a missed entry from https://github.com/spinnaker/igor/pull/745

chore(docker): remove v1 docker tag migrator

---

igor-monitor-artifactory/src/main/java/com/netflix/spinnaker/igor/artifactory/ArtifactoryBuildMonitor.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/PluginsBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/JenkinsBuildMonitor.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitor.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java

Two main changes here:
1. Add a metric for when we skip sending events (same as [`DockerMonitor`](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy#L155)
2. Mark the build processed even if we don't send an event to `echo` (because we are fast-forwarding), again same as [`DockerMonitor`](https://github.com/spinnaker/igor/blob/master/igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy#L150)
The idea behind #2 is that when we have two `igor`s: one actively sending events, the other just fast-forwarding to be ready to send events if needed.
When we switch which `igor` triggers events to `echo`, we need to make sure we don't double trigger on builds in the past. Without this change, we …

fix(jenkins): mark builds processed when fastforwarding

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy

This PR is to fix spinnaker/spinnaker#5803. There is a small chance that the property file is not immediately available after build completes.
This PR adds retry on 404 when getting property file from Jenkins build, in addition to network/5XX errors.
Before this PR, if Jenkins return 404 on getPropertyFile it will not retried and the Jenkins stage will immediately fail. User will have to restart the stage just to get the build artifact.
After this PR, Igor will retry up to 5 times with 2 seconds non-exponential backoff if Jenkins return 404 code.

feat(jenkins): Retry on 404 when getting build artifact

---

igor-monitor-artifactory/src/test/java/com/netflix/spinnaker/igor/artifactory/model/ArtifactoryItemTest.java

Replaced the deprecated getMetadata with a call to getMetadata(String key) to get the specific key of interest.

refactor(artifacts): Remove deprecate getMetadata

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/IgorConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerService.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/config/TravisConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/main/resources/hystrix.properties
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsServiceSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java

Only one place where Hystrix was actually used for fallbacks, which I migrated. Everything else was just removed.

refactor(*): Replace Hystrix with Resilience4j

---

igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginInfo.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseService.java
igor-monitor-plugins/src/main/java/com/netflix/spinnaker/igor/plugins/model/PluginRelease.java
igor-monitor-plugins/src/test/groovy/com/netflix/spinnaker/igor/plugins/front50/PluginReleaseServiceSpec.groovy

It will be useful to have this data on the plugin trigger.
Related to:
https://github.com/spinnaker/orca/pull/3756
https://github.com/spinnaker/echo/pull/949

feat(plugins): Add description and provider to PluginRelease

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy

Stop a build can mean a) stopping it or b) removing it from the queue if hasn't started.
Today, igor, will attempt both if the build has been started. This can cause a 500 from jenkins server which is propagated to orca which then fails to actually complete the cancellation of a pipeline.
(it's mostly harmless but it can cause issues and it also generates a bunch of exception noise)
This change stops the build if it was started OR removes it from the queue if it wasn't started not both

fix(jenkins): Stop or delete from queue

---

igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ClusterInfoService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ConcourseClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/SkyServiceV2.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/TokenServiceV2.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/ClusterInfo.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/TokenV2.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/concourse/client/ConcourseClientSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/concourse/ConcourseBuildMonitorTest.java

* fix(concourse): support old and new concourse auth
Fixes concourse authentication for clusters >= v6.1.0 by detecting version and providing different implementation accordingly.
Addresses issue: https://github.com/spinnaker/spinnaker/issues/5797
* fix(concourse): support old and new concourse auth
Sending basic auth header to /info endpoint causes 401
Addresses issue: https://github.com/spinnaker/spinnaker/issues/5797
Co-authored-by: Jared Stehler <jared.stehler@edgenuity.com>

fix(concourse): support old and new concourse auth (#762)

---

igor-web/src/main/java/com/netflix/spinnaker/igor/artifacts/ArtifactController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/artifacts/ArtifactService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactServiceSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/artifacts/TestArtifactService.java

Adds a `type` parameter to the `ArtifactService` interfaces methods such that we can query different types of artifacts (not just Debian).

feat(artifacts): Add type parameter to ArtifactService

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ConcourseClient.java

The backport cherry-picked the fix, but `Slf4jRetrofitLogger` was added in a prior commit I guess.
Interestingly, the https://github.com/spinnaker/igor/pull/824 PR's check and build didn't catch this 🤔

fix(concourse): backport did not include missing class

---

gradle.properties
igor-core/src/main/java/com/netflix/spinnaker/igor/build/artifact/decorator/DebDetailsDecorator.java
igor-core/src/main/java/com/netflix/spinnaker/igor/build/artifact/decorator/RpmDetailsDecorator.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/GitlabCiBuildMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/model/Plan.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java

This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.

chore(spotless): upgrade spinnaker gradle plugin

---

igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/service/ConcourseService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/concourse/service/ConcourseServiceSpec.groovy

Sets branch name to the sha1 short-ref if missing from concourse metadata
fixes https://github.com/spinnaker/spinnaker/issues/5942

fix(concourse): handle missing branch in git metadata

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitHubConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubMaster.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/scm/github/client/model/GetRepositoryContentResponse.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubMasterSpec.groovy

Add support for retrieving managed delivery manifests from GitHub repos.
Also fixed GitHub deprecated API authentication through query parameters (https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/)

feat(managed-delivery): Retrieve Managed Delivery manifests from GitHub

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/Main.groovy

This annotation is useful as a way of consistently obtaining the Main class package in our services so we can determine package information, like version, at runtime.

chore(*): Use SprintBootApplication annotation on Main class

---

igor-core/src/main/java/com/netflix/spinnaker/igor/build/model/GenericBuild.java
igor-web/src/main/java/com/netflix/spinnaker/igor/ci/CiBuildService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/ci/CiController.java

- adding build number and commit id to generic CI service endpoint
- adding `NoArgsConstructor` and `AllArgsConstructor` to `GenericBuild`

feat(ciService): add more fields to generic ci service

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

Netflix is adding a flag called `includeDetails` to `getImagesByAccount` endpoint, in order to get a detailed response from the docker registry (with details like commit id, build number etc. that we are currently caching).
This would not effect the current behavior of `getImagesByAccount`, as this is an optional query param.

feat(includeDetails): changing includeDetails flag to true

---

igor-web/igor-web.gradle
igor-web/src/main/java/com/netflix/spinnaker/igor/config/HelmConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/HelmMonitor.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/accounts/ArtifactAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/accounts/HelmAccount.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/accounts/HelmAccounts.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/accounts/HelmAccountsService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/cache/HelmCache.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/cache/HelmKey.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/model/HelmEntry.java
igor-web/src/main/java/com/netflix/spinnaker/igor/helm/model/HelmIndex.java
igor-web/src/main/java/com/netflix/spinnaker/igor/history/model/HelmEvent.java

- Helm polling/caching/triggering
- Models and etc. for Helm repository information
Relates to issue: https://github.com/spinnaker/spinnaker/issues/4447 
Related PRs:
https://github.com/spinnaker/echo/pull/988
https://github.com/spinnaker/deck/pull/8475
https://github.com/spinnaker/clouddriver/pull/4773

feat(helm): Add Helm repo polling and caching

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy

This configuration worked fine in okhttp2, but not in okhttp3.
As a workaround, Igor will try to use the keystore as a truststore as well, and prints a warning in the log.
"Bug" introduced in https://github.com/spinnaker/igor/pull/834. Keystore support was added in https://github.com/spinnaker/igor/pull/596.

fix(jenkins): Igor fails to start if only keystore is configured

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java

Adds some more info about the pipeline that triggered the Travis build. Piggybacking on the functionality added in #414.
Screenshot from Travis before and after the change:

feat(travis): Adds more info to triggered Travis builds by default

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

Docker triggers might not send an event to echo if the cache was empty (e.g. instance just came)
Adding a reason to event to metric for this case

fix(docker): use a more concrete reason for when the cache is empty

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/StashConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/WerckerConfig.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/config/HelmConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/KeelConfig.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/stash/client/StashClientSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerClientSpec.groovy

Make it more consistent logging wise (`echo` client had logging set to NONE 😱 )

fix(retrofit): Use the retrofit log level bean from retrofit configuration in kork-web

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/DockerMonitor.groovy

We have seen an intermittent issue wherein the same docker image is found as new and thus Igor sends multiple events to Echo.  Adding this log here should help verify the theory that we are indeed seeing the same image as new multiple times.

fix(docker): Log imageIds when logging new images found

---

igor-web/src/main/java/com/netflix/spinnaker/igor/ci/CiBuildService.java
igor-web/src/main/java/com/netflix/spinnaker/igor/ci/CiController.java

As a part of our effort to open source the CI view in Spinnaker, we have 2 endpoints which power this view:
1. get all builds, based on a project and repo names.
2. for each build, get the build log.
We already added the first hook (#1). This PR is adding the second hook to fetch the build log.
In order to use these hooks, you'll have to implement a `CiBuildService` in your `igor` fork, with concrete implementation to those two endpoints.
The CI view will call those endpoints from `deck` (the UI) via `gate`.

feat(buildLog): adding build log hook

---

igor-web/igor-web.gradle
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java

to clean up warnings like:
```
2020-12-14 19:20:54.704  WARN 1 --- [   scheduling-1] c.n.s.okhttp.OkHttp3MetricsInterceptor   : Request GET:https://jenkins.<mydomain>/job/<somejob>/job/master/api/xml?exclude=/*/build/action[not(totalCount)]&tree=builds[number,url,duration,timestamp,result,building,url,fullDisplayName,actions[failCount,skipCount,totalCount]] is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:95)
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:33)
at com.netflix.spinnaker.igor.jenkins.service.JenkinsService.lambda$getBuilds$4(JenkinsService.java:163)
at …
```

chore(logs): allow anonymous calls to jenkins to get builds and projects

---

igor-core/src/main/java/com/netflix/spinnaker/igor/build/model/UpdatedBuild.java
igor-core/src/main/java/com/netflix/spinnaker/igor/service/BuildOperations.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/service/JenkinsService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

This supports `orca` updating the description of a
running/completed job (cannot be queued) and deep linking
back to the execution view.
```
curl -X "PATCH" "https://localhost:8085/masters/my_master/jobs/my_job_name/update/553" \
-H 'Content-Type: application/json' \
-d $'{
"description": "This build was triggered by a super swsssssseet <a href=\\"https://spinnaker/#/applications/my_app/executions/details/01EX5E3FT7PVSRNGS44EHCDPDF\\">Spinnaker</a>."
}'
```

feat(jenkins): Support for updating job description

---

igor-core/src/main/java/com/netflix/spinnaker/igor/build/model/GenericArtifact.java
igor-core/src/main/java/com/netflix/spinnaker/igor/build/model/GenericBuild.java
igor-core/src/main/java/com/netflix/spinnaker/igor/build/model/GenericGitRevision.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsProperties.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/docker/service/TaggedImageList.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/JenkinsClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/jenkins/client/model/Build.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubClient.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/client/GitHubMaster.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/github/client/model/Commit.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/scm/AbstractScmMaster.java

- add extra necessary fields to Git and Build data structure for CiBuild support
- add calls to jenkins and github to pull commit details and build info
- add property field to enable CiBuild integration
/cc @luispollo 
/cc @gal-yardeni

feat(CiBuild): extend Jenkins / Docker / Github clients with REST calls

---

.github/workflows/scheduled_release.yml

Similarly to what we've done for Keel recently, this PR adds a new GitHub action to automatically trigger a weekly release for Igor such that we don't have to manually cut releases. This is intended to enable other organizations consuming releases outside of Netflix.

chore(release): Add weekly release

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy

Fix issue https://github.com/spinnaker/spinnaker/issues/6217.
Here is what happens now :
* buildNumber gets casted from null to "null" when calling `pendingOperationsCache.setOperationStatus(pendingKey, PendingOperationsCache.OperationStatus.COMPLETED, buildNumber)`
* Next call from orca evaluate `!Strings.isNullOrEmpty(pendingStatus.value)` as true and returns "null" as job identifier thus breaking the next step.

fix(jenkins): Using null breaks the cache mechanism

---

igor-monitor-artifactory/igor-monitor-artifactory.gradle

after Bintray sunset this artifact moved to Maven Central, however only version 2.9.2 is available

chore(dependencies): bump artifactory-java-client-services version to 2.9.2

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java

After upgrading from Travis Enterprise 2 to 3, we ran into an issue where the build was `null` for some jobs. I believe this  is a bug in Travis, but I'm adding a check here to just avoid a NullPointerException that blocks the Travis provider from fetching builds if this issue should ever occur again.

fix(travis): Avoid a potential NPE when retrieving latest builds

---

.idea/compiler.xml
.idea/gradle.xml
build.gradle
gradle.properties
igor-bom/igor-bom.gradle
igor-core/igor-core.gradle
igor-monitor-artifactory/igor-monitor-artifactory.gradle
igor-monitor-plugins/igor-monitor-plugins.gradle
igor-monitor-travis/igor-monitor-travis.gradle
igor-web/igor-web.gradle

There is an issue in the Plugins Framework that was solved in this PR: spinnaker/kork#866
but this fix was released in kork 7.110.0
I bumped the version of kork to include the fix in VersionManager in the plugins framework but this involved changing the groupId of kork because now it's been published under "io.spinnaker" and this release branch is pretty old.
I had to bump the version of Fiat as well because it has issues when trying to download the kork version in fiat due to the groupId change.

fix(build): bump kork to 7.110.0 & change groupid for dependencies

---

igor-core/igor-core.gradle
igor-monitor-travis/igor-monitor-travis.gradle
igor-web/igor-web.gradle

While upgrading spring cloud to Hoxton.SR12, we encountered below errors :
```
> Task :igor-core:compileGroovy
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:20: error: package javax.validation does not exist
import javax.validation.Valid;
^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactDecorationProperties.java:21: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;
^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:24: error: package javax.validation does not exist
import javax.validation.Valid;
^
/igor/igor-core/src/main/java/com/netflix/spinnaker/igor/config/ArtifactTemplateProperties.java:25: error: package …
```

fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactExtractor.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/artifacts/ArtifactExtractorSpec.groovy
igor-web/src/test/java/com/netflix/spinnaker/igor/artifacts/ArtifactExtractorTest.java

Using the Spring Boot provided ObjectMapper instead of instantiating it manually automatically give us a jackson mapper with the correct module loaded (it's already available on the classpath).
The error we're seing:
```
c.n.s.igor.artifacts.ArtifactExtractor   : Error processing JSON: {}
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.netflix.spinnaker.igor.build.model.GenericBuild["scm"]->java.util.Collections$SingletonList[0]->com.netflix.spinnaker.igor.build.model.GenericGitRevision["timestamp"])
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionExcepti …
```

fix(artifacts): ArtifactExtractor is unable to deserialize jsr310 dates

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

When defining a Jenkins job inside folders, the name contains slashes. Because of that, instead of matching the request to the IGOR STOP endpoint (`/masters/{name}/jobs/{jobName}/stop/{queuedBuild}/{buildNumber}`), Spring is matching the request to the BUILD one (`/masters/{name}/jobs/**`) because it accepts anything after the last slash.
I have tried to avoid adding a new endpoint by modifying the existing one to accept anything between `jobs` and `stop` (e.g. `/masters/{name}/jobs/**/stop/{queuedBuild}/{buildNumber}`)and parse the job name manually, but it is still matching the other endpoint. 
Related Orca PR: https://github.com/spinnaker/orca/pull/4294

feat(jenkins): Stop Jenkins job when job name has slashes in the job name

---

igor-web/igor-web.gradle

The property spring.config.additional-location is redundant in igor-web.gradle file. This property is set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.igor.Main. So removing it from gradle file.

refactor(web): Clean up redundant spring property in gradle file

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/gitlabci/client/model/PipelineStatus.java

Fixes spinnaker/spinnaker#6754
Added all Gitlab API's documented pipeline statuses, and also added a special one `unknown` which will be the default for any others that are added in the future to avoid breaking the GitlabCiClient.

fix(gitlabci): Fixed JSON parsing exceptions for unknown GitlabCI pipeline statuses

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/TravisCache.java

I noticed not all cached keys will be deleted by Igor, leading to a slow, but steady buildup of keys. Resolving by expiring them after 60 minutes. No need to make this user configurable.

feat(travis): Add redis TTL for queue keys

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Log.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/client/TravisClientSpec.groovy
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

We've had lots of trouble with the `log_complete` feature Travis added a while back on our request. It was supposed to solve our issues with figuring out when logs are _actually_ available (which can be up to several minutes after the build is complete) - but basically it can't be trusted. We've seen cases where it turns to `true` even before the _build_ was completed (how can the logs be done then? 😆), and also in the opposite case, it can return `false` for a long time even though the logs _are_ in fact complete. So it's better to just fall back to the old way of checking log completion (**with some improvements***). We've been running this internally in Schibsted for several months, and have not seen any issues with log fetching during that time - a huge improvement from earlier!
\* …

fix(travis): Enable legacy log fetching

---

igor-core/src/main/java/com/netflix/spinnaker/igor/build/BuildCache.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/TravisBuildMonitor.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/TravisBuildMonitorSpec.groovy

This fixes a rare bug where some builds will "be lost" and not trigger any pipelines. Because we effectively set the TTL to 5 minutes instead of 5 hours, Spinnaker would quickly stop tracking builds. Usually this is no problem because they will be present in the builds returned from the Travis API, but if the `numberOfJobs` property is set too low or during periods with a lot of simultaneous builds, this could cause builds (especially long running ones) to be lost.

fix(travis): Redis TTL is given in seconds, not minutes

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Log.java

Came across another variation: "Your build has been stopped". Adding it and tidying up the code a bit.

feat(travis): Add another Travis termination string

---

igor-web/igor-web.gradle
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountFactoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildAccountRepositoryTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildExecutorTest.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java
igor-web/src/test/java/com/netflix/spinnaker/igor/MainTest.java
igor-web/src/test/java/com/netflix/spinnaker/igor/artifacts/ArtifactExtractorTest.java

Before refactor, total test cases executed were 474, 1 ignored. 
After refactor, total test cases executed are 474, 1 ignored.

refactor(tests): convert junit4 based testcases to junit5 and clean up in igor

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.slim

Default containers will use JRE 17. Versions using JRE 11 will also be published to allow opting out if required.

chore(build): default containers to JRE 17

---

igor-monitor-travis/igor-monitor-travis.gradle
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

To make use of custom spinnaker exception instead of RetrofitError using SpinnakerRetrofitErrorHandler present in kork service, to rectify dependency of RetrofitError class

refactor(travisclient): make changes to travisClient to use Spinnaker custom exception instead of RetrofitError using SpinnakerRetrofitErrorHandler

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
build.gradle
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/client/logparser/ArtifactParserTest.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/wercker/WerckerBuildMonitor.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/concourse/service/ConcourseServiceSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/bitbucket/CommitControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/github/CommitControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/gitlab/CommitControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/stash/CommitControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerServiceSpec.groovy

`fastTime` and `size` are no longer accessible fields. Replace with `getTime()` and `size()` respectively. IntelliJ shows no remaining access related issues (not to say there aren't more hiding).
Additionally, run tests using JRE 17 to catch this stuff earlier.
Note: this does **not** resolve the issue reported relating to `Instant.seconds` - further PR to come in Kork for that one.

fix(java17): resolve remaining access to private fields, run tests on JRE 17

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/WerckerConfig.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/wercker/WerckerClientSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/6881
If no converter is set for a RestAdapter it defaults to Gson, which uses reflection to set fields. JRE 17 says no bueno to that on classes like `Instant` that are now making fields inaccessible.

fix(java17): add Jackson converter to RestAdapters to avoid Gson

---

igor-web/igor-web.gradle

While upgrading groovy from 2.5.15 to 3.0.10, encountered following error during igor-web:test :
```
> Task :igor-web:compileTestGroovy
startup failed:
/igor/igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/InfoControllerSpec.groovy: 32: unable to resolve class groovy.json.JsonSlurper
@ line 32, column 1.
import groovy.json.JsonSlurper
^
1 error
> Task :igor-web:compileTestGroovy FAILED
```
To resolve this issue added testImplementation of org.codehaus.groovy:groovy-json in igor-web.gradle.

chore(dependency): add testImplementation of groovy-json dependency while upgrading to groovy 3.x

---

igor-web/src/main/java/com/netflix/spinnaker/igor/scm/ManagedDeliveryScmController.java
igor-web/src/main/java/com/netflix/spinnaker/igor/scm/ManagedDeliveryScmService.java
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/ManagedDeliveryScmControllerSpec.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/scm/ManagedDeliveryScmServiceSpec.groovy

Allow retrieval of raw delivery configuration manifests which is
required by Keel.
https://github.com/spinnaker/keel/blob/master/keel-igor/src/main/kotlin/com/netflix/spinnaker/keel/igor/ScmService.kt#L44

feat(scm): add ability to retrieve raw delivery config

---

igor-monitor-travis/igor-monitor-travis.gradle

While upgrading spring boot 2.6.15, encounter below errors in igor-monitor-travis module during build:
```
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.java:26: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlRootElement;
^
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Build.java:38: error: cannot find symbol
@XmlRootElement(name = "builds")
^
symbol: class XmlRootElement
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/client/model/v3/V3Branch.java:22: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlRootElement;
^
/igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/ …
```

chore(dependency): add explicit dependency of jaxb-api while upgrading spring boot 2.6.x

---

igor-web/igor-web.gradle

While upgrading spring boot 2.6.15, encounter below errors in igor-web module during build:
```
> Task :igor-web:compileGroovy
startup failed:
/igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/JenkinsConfig.groovy: 22: unable to resolve class com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule
@ line 22, column 1.
import com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule
^
1 error
> Task :igor-web:compileGroovy FAILED
```
To fix this issue, adding explicit dependency of jackson-module-jaxb-annotations in igor-web.gradle. Since jackson-module-jaxb-annotations is a transitive dependency of [spring boot](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.15/spring-boot-dependencies-2.6.15.pom) both 2.5.x and 2.6.x, pinning the …

chore(dependency): add explicit dependency of jackson-module-jaxb-annotations while upgrading spring boot 2.6.x

---

igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java

While upgrading spring boot 2.6.15, encounter below errors in igor-web module during test compilation:
```
> Task :igor-web:compileTestJava FAILED
/igor/igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java:21: error: cannot find symbol
import static org.mockito.Mockito.verifyZeroInteractions;
^
symbol:   static verifyZeroInteractions
location: class Mockito
/igor/igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java:119: error: cannot find symbol
verifyZeroInteractions(echoService);
^
symbol:   method verifyZeroInteractions(EchoService)
location: class NexusEventPosterTest
/igor/igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java:129: error: cannot find symbol
verifyZeroInteractions(echoService);
^ …
```

refactor(web/test): replace deprecated mockito api verifyZeroInteractions() with verifyNoMoreInteractions() during upgrade to spring boot 2.6.x

---

igor-core/igor-core.gradle
igor-core/src/main/java/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java
igor-core/src/main/java/com/netflix/spinnaker/igor/polling/CommonPollingMonitorInstrumentation.java
igor-core/src/test/groovy/com/netflix/spinnaker/igor/polling/CommonPollingMonitorTest.groovy

Fixes https://github.com/armory-plugins/armory-observability-plugin/issues/34. 
Long overdue, I know, as we have been running with it for more than a year now and forgot to upstream it 😓  
Relevant polling gauges are currently always **NaN**: they represent new items (e.g images cached) or above the limit, requiring manual intervention (via admin endpoint).
The lack of visibility over these metrics (just visible in logs) might be a big issues, given blocked caching might have consequences like engineers not be able to find they releases or triggers not firing.
The PR fixes this using the spectator library, trying to achieve a similar outcome we use internally at Wise in our production services with Micrometer, i.e. registering some variables with strong references and letting Prometheus …

Telemetry: fix polling gauges always reporting NaN on Prometheus and timers

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/build/BuildController.groovy
igor-web/src/test/groovy/com/netflix/spinnaker/igor/build/BuildControllerSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/6928
The implementation of: 
```
feature:
igor:
jobNameAsQueryParameter: true
```
did not include the support  for Jenkins artifacts and property files leading to failures on Manual triggers and rerun's of a Spinnaker pipeline retrieving BuildInfo from the sub-folder Jenkins job.

fix(jenkins): Enable properties and artifacts with job name as query parameter

---

igor-web/igor-web.gradle

since it's meant for migration only
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#configuration-properties for background.

chore(dependencies): remove org.springframework.boot:spring-boot-properties-migrator

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
build.gradle
gradle.properties

- Swap the `setup-java` versions around so that 17 comes first on the PATH.
- Update build commands to enable cross compilation plugin.
Build should pass once https://github.com/spinnaker/spinnaker-gradle-project/pull/203 and https://github.com/spinnaker/spinnaker-gradle-project/pull/204 are both merged.
Confirmed it's working with `targetJava17=false`:
```
javap -v igor-web/build/classes/groovy/main/com/netflix/spinnaker/igor/Main | grep major
Warning: File ./igor-web/build/classes/groovy/main/com/netflix/spinnaker/igor/Main.class does not contain class igor-web/build/classes/groovy/main/com/netflix/spinnaker/igor/Main
major version: 55
```
and `true`:
```
javap -v igor-web/build/classes/groovy/main/com/netflix/spinnaker/igor/Main | grep major
Warning: File …
```

feat(java17): compile with JDK17 targeting Java 11 bytecode

---

igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/service/TravisService.java
igor-monitor-travis/src/test/groovy/com/netflix/spinnaker/igor/travis/service/TravisServiceSpec.groovy

When populating the build dropdown for manual executions, manually triggered builds are missing for Travis Enterprise version 3.0.54 and newer. Before these builds had the same `event_type=push` as other builds, but now they have `event_type=api`. Adding `api` to the filtering fixes the issue.

fix(travis): Properly return API triggered builds

---

igor-monitor-travis/igor-monitor-travis.gradle
igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/BitBucketConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitHubConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitLabConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitlabCiConfig.java
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/StashConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/scm/bitbucket/client/BitBucketMaster.groovy
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/ConcourseClient.java
igor-web/src/main/java/com/netflix/spinnaker/igor/concourse/client/OkHttpClientBuilder.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/HelmConfig.java

Moving away from `com.squareup.okhttp.OkHttpClient` to `okhttp3.OkHttpClient` to avoid any unwanted dependency conflicts.
okhttp3.OkHttpClient for retrofit1 is provided by [Ok3Client](https://github.com/JakeWharton/retrofit1-okhttp3-client)

refactor(retrofit): replace OkClient with Ok3Client

---

igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/DockerRegistryConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy
igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/PluginMonitorConfig.java
igor-web/src/main/java/com/netflix/spinnaker/igor/config/KeelConfig.java

Along with https://github.com/spinnaker/kork/pull/1233, this PR fixes any issues arising due to the addition of Retrofit2EncodeCorrectionInterceptor to the OkHttpClient used for retrofit1 client.

refactor(retrofit1): make sure Retrofit2EncodeCorrectionInterceptor is not included in the retrofit1 clients
